interface IRoutes {
    HOME: string;
    VIEW: string;
    EARNCOINS: string;
    HOME_LANDING: string;
    VIEW_LANDING: string;
    EARNCOINS_LANDING: string;
    LOGIN: string,
    TABLIST: string,
    LOGOUT: string,
    AUTH: string;
    ONBORDING: string;
    MYCAMPAIGN: string;
    SETTING: string;
    MYCAMPAIGN_LANDING: string;
    SETTING_LANDING: string;
    SHOWADDS: string;
    CAMPAIGNLANDING: string;
};
export const ROUTES: IRoutes = {
    HOME: "HOME",
    VIEW: "VIEW",
    EARNCOINS: 'EARNCOINS',
    HOME_LANDING: "HOME_LANDING",
    VIEW_LANDING: "VIEW_LANDING",
    EARNCOINS_LANDING: "EARNCOINS_LANDING",
    LOGIN: "LOGIN",
    TABLIST: "TABLIST",
    LOGOUT: 'LOGOUT',
    AUTH: 'AUTH',
    ONBORDING: "ONBORDING",
    MYCAMPAIGN_LANDING: 'CREATECAMPAIGN_LANDING',
    SETTING_LANDING: 'SETTING_LANDING',
    MYCAMPAIGN: "CREATECAMPAIGN",
    SETTING: 'SETTING',
    CAMPAIGNLANDING: 'CAMPAIGNLANDING'
}