interface IRoutes {
    HOME: string;
    VIEW: string;
    EARNCOINS: string;
    HOME_LANDING: string;
    VIEW_LANDING: string;
    EARNCOINS_LANDING: string;
    CREATE_CAMPAIGN: string;
    LOGIN: string,
    TABLIST: string,
    LOGOUT: string,
    AUTH: string;
    ONBORDING: string;
    INTRODUCATION: string;
    FORGOTPASSWORD: string;
    CREATEACCOUNT: string;
    MYCAMPAIGN: string;
    SETTING: string;
    MYCAMPAIGN_LANDING: string;
    SETTING_LANDING: string;
    VIEWCOIN: string;
    CREATECAMP: string;
    INVITEFRIEND:string;
    ADDVIDEO: string;
    EDITPROFILE:string;
    BUYCOIN:string;
};
export const ROUTES: IRoutes = {
    HOME: "HOME",
    VIEW: "VIEW",
    EARNCOINS: 'EARNCOINS',
    HOME_LANDING: "HOME_LANDING",
    VIEW_LANDING: "VIEW_LANDING",
    EARNCOINS_LANDING: "EARNCOINS_LANDING",
    CREATE_CAMPAIGN: "CREATE_CAMPAIGN",
    LOGIN: "LOGIN",
    TABLIST: "TABLIST",
    LOGOUT: 'LOGOUT',
    AUTH: 'AUTH',
    ONBORDING: "ONBORDING",
    INTRODUCATION: 'INTRODUCATION',
    FORGOTPASSWORD: 'FORGOTPASSWORD',
    CREATEACCOUNT: "CREATEACCOUNT",
    MYCAMPAIGN_LANDING: 'CREATECAMPAIGN_LANDING',
    SETTING_LANDING: 'SETTING_LANDING',
    MYCAMPAIGN: "CREATECAMPAIGN",
    SETTING: 'SETTING',
    VIEWCOIN: 'VIEWCOIN',
    CREATECAMP: 'CREATECAMP',
    INVITEFRIEND:"INVITEFRIEND",
    ADDVIDEO: "ADDVIDEO",
    EDITPROFILE:"EDITPROFILE",
    BUYCOIN:"BUYCOIN"
}