export const type = {
    FULL_NAME: "FULL_NAME",
    EMAIL: "EMAIL",
    PASSWORD: "PASSWORD",
    CONFIRM_PASSWORD: "CONFIRM_PASSWORD",
    SHOW_PASSWORD: "SHOW_PASSWORD",
    CONFIRM_PASSWORD_SHOW: "CONFIRM_PASSWORD_SHOW",
    EMPTY_STATE: "EMPTY_STATE",
    FULLNAME_ERROR: "FULLNAME_ERROR",
    EMAIL_ERROR: "EMAIL_ERROR",
    PASSWORD_ERROR: "PASSWORD_ERROR",
    CONFIRM_PASSWORD_ERROR: "CONFIRM_PASSWORD_ERROR"
}