import { Dimensions, Platform, StyleSheet } from 'react-native';
import { Fonts } from '../assets';
import { Colour } from '../theme';

export const commonStyles = StyleSheet.create({
  errorText: {
    color: 'red',
    marginLeft: 5,
    marginBottom: 2,
    fontFamily: Fonts.NotoSansLight,
    fontSize: 12,
  },
  backButtonText: {
    fontSize: 14,
    fontFamily: Fonts.QuicksandSemiBold,
    fontWeight: '600',
    color: Colour.PrimaryBlue,
    marginLeft: 21,
  },
  boxshado: {
    backgroundColor: '#fff', borderRadius: 14, shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 8,

    elevation: 5,
  },
  errorText2: {
    color: Colour.gray500,
    marginLeft: 5,
    textAlign: 'left',
    fontFamily: Fonts.NotoSansLight,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '300',
  },
  blueBackGround: {
    backgroundColor: Colour.PrimaryBlue,
    flex: 1,
    height: '100%',
    width: '100%',
  },
  whiteBG: {
    backgroundColor: Colour.white,
    flex: 1,
  },
  title: {
    textAlign: 'center',
    fontFamily: Fonts.QuicksandBold,
    fontSize: 24,
    lineHeight: 32,
    color: Colour.white,
  },
  subTitle: {
    textAlign: 'center',
    fontFamily: Fonts.QuicksandBold,
    fontSize: 18,
    lineHeight: 32,
    color: Colour.white,
  },
  subText: {
    textAlign: 'center',
    fontFamily: Fonts.NotoSansMedium,
    fontSize: 14,
    color: Colour.white,
  },
  forgotPwdTitle: {
    marginTop: 24,
    marginBottom: 8,
    textAlign: 'center',
    fontFamily: Fonts.InterSemiBold,
    fontSize: 24,
    lineHeight: 32,
    fontWeight: '600',
    color: Colour.darkGray,
    textAlignVertical: 'top',
  },
  forgotPasswordSubText: {
    textAlign: 'center',
    fontFamily: Fonts.NotoSansLight,
    fontSize: Platform.OS === 'ios' ? 14 : 16,
    fontWeight: '300',
    color: Colour.gray500,
  },
  forgotTextInput: {
    backgroundColor: Colour.white,
    borderRadius: 8,
    height: 44,
    color: Colour.gray500,
    fontFamily: Fonts.NotoSansLight,
    fontWeight: '300',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderColor: Colour.gray300,
    borderWidth: 1,
  },
  forgotSubText: {
    fontFamily: Fonts.NotoSansRegular,
    fontSize: 14,
    textAlign: 'left',
    textAlignVertical: 'top',
    color: Colour.gray700,
    marginTop: 10
  },
  main: {
    backgroundColor: Colour.white,
    height: 65,
    borderRadius: 18,
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 16,

    shadowOpacity: 0.23,
    flex: 1,
    shadowColor: Colour.gray200,
    borderWidth: 0,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowRadius: 2,
    paddingLeft: 8,
    paddingRight: 8,
  },
  column: {
    flexDirection: 'column',
    flex: 1,

  },
  row: {
    flexDirection: 'row',
    flex: 1,
  },
  rightIconBorder: {
    borderRadius: 6,
    height: 20,
    width: 20,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',

    borderColor: Colour.PrimaryBlue,
  },
  bigCardBorder: {
    borderWidth: 1,
    borderColor: Colour.gray200,
    borderRadius: 18,
    padding: 16,
  },
  grayBorder: {
    backgroundColor: Colour.gray100,
    width: '100%',
    height: 1,
  },
  grayTextInputBorder: {
    borderWidth: 1,
    borderColor: Colour.gray300,
    backgroundColor: Colour.white,
    borderRadius: 8,
    paddingVertical: 0,
    height: 44,
    color: Colour.gray900,
    fontFamily: Fonts.NotoSansLight,
    paddingHorizontal: 14,
    marginTop: 6,
    marginBottom: 6,
  },
  accountTitle: {
    fontFamily: Fonts.QuicksandSemiBold,
    fontSize: 14,
    lineHeight: 22,
    textAlign: 'left',
    textAlignVertical: 'top',
    fontWeight: '600',
    color: Colour.PrimaryBlue,
    marginBottom: 16,
  },
  textinputText: {
    fontFamily: Fonts.NotoSansLight,
    fontSize: 16,
    lineHeight: 24,
    textAlign: 'left',
    textAlignVertical: 'top',
    fontWeight: '300',
    color: Colour.gray900,
    marginBottom: 16,
  },
  withoutborderCard: {
    backgroundColor: '#FFF',
    borderRadius: 14,
    shadowColor: Colour.gray200,

    shadowOffset: {
      width: 0,
      height: 2,
    },
    padding: 16,
    bottom: 80,
    position: 'absolute',
    elevation: 5,
    shadowRadius: 2,
    shadowOpacity: 0.23,
    width: '100%',
  },
  dropdownPlaceHolder: {
    color: Colour.gray500,
    fontFamily: Fonts?.NotoSansLight,
    fontSize: 16,
    fontWeight: '500',
  },
});
