export const String: any = {
    pageTitle2: 'Easy intergration',
    pageTitle3: `Save $$$ at 100’s of \nlocal stores`,
    pageTitle3Sub: 'local stores',
    page: {
        p1: 'Centavizer works with your favourite',
        p2: 'fitness tracker or smartphone to award',
        p3: 'cash or "centz" for every step you take',
        p4: 'Centavizer works with your favourite fitness tracker or',
        p5: 'fitness trackerand awards cash for every step',
        p6: 'Centavizer connects with your smart phone',
        p7: 'or fitness trackerand awards cash',
        p8: 'for every step'
    },
    page1: 'Centavizer works with your favorite\n fitness tracker and awards you for\n taking steps to a healthy lifestyle.',
    page2: 'Simply connect  the centavizer app  with your\n smart phone and  fitness tracker and earn Centz\n for every step you take.',
    page3: `We’ve partnered with local and national\n companies and merchants to offer you\n product discounts on everyday purchases.`,
    alreadyMember: 'Already a member?',
    login: 'Login',
    skip: 'Skip',
    fbTitle: 'Signup with Facebook',
    createAcc: 'Create account',
    password: 'password',
    emailAdd: 'Email address',
    google: 'Signup with Google',
    apple: 'Signup with Apple',
    or: 'or',
    createAccount: 'Create your account',
    loginWithApple:'Login with Apple',
    loginWithGoogle:'Login with Google',
    loginWithFacebook:'Login with Facebook',
    email: 'Email',
    keyboardEmail: 'email-address',
    keybordNext: 'next',
    keybordnum: 'numeric',
    keybordNone: 'none',
    go: 'go',
    handled: 'handled',
    loginAccout: 'Login to your account',
    Login: 'Login',
    forgotPws: 'Forgotten your password?',
    serchDeal: 'search deals',
    centzBank: 'Your Centz Bank',
    learnMore: 'learn more',
    balence: 'Available balance',
    saving: 'Savings this month',
    exploreDeals: 'Explore deals',
    allCategory: 'all categories',
    AllCategory: 'All categories',
    featureDeal: 'Featured deal',
    allDeal: 'all deals',
    status: 'Your stats',
    history: 'view stat history',
    businesses: 'Favorite businesses',
    seeAll: 'See all',
    infographicsTitle: 'How much can I make?',
    infographicsTitle2: 'Make $0.10 per step you take',
    infographicsSubTitle1: 'Cursus neque, orci massa lectus egestas sed malesuada.',
    infographicsTitle3: 'Make $0.10 per hour you sleep',
    infographicsTitle4: 'Find deals near you',
    infographicsTitle5: 'Get discounts on the Centavizer Marketplace',
    Marketplace: 'Marketplace',
    infoTitle1: 'Where can I spend my Centz?',
    infoTitle: 'What is Centavizer?',
    lightContent: 'light-content',
    fitnessTracker: 'Using a fitness tracker?',
    sumsungHelth: 'Samsung\nHealth',
    tracker: {
        t1: 'Integrate your fitness tracker now and get',
        t2: '$10.00',
        t3: 'into your Centz bank and a credit of 28 \n days of activity!',

    },
    syncTracer: 'Sync your track',
    appleHealth: 'Apple\nHealth',
    fitbit: 'Fitbit',
    syncReady: 'Synced & ready!',
    syncSubText: 'Your Fitness tracker has been synced \nsuccesfully.\n\nNow you can start earning Centz.',
    continue: 'Continue',
    darkContent: 'dark-content',
    googleFit: 'Google Fit',
    backToLogin: 'Back to log in',
    submit: 'Submit',
    conformPwd: 'Confirm password',
    resetPwd: 'Reset password',
    recentSearches: 'Recent searches',
    clere: 'Clear',
    forgotPasswordStep1: {
        forgotPwdTitle: 'Forgot password?',
        subTitle: 'No worries, we’ll send you reset instructions.',
        enterEmail: 'Enter your email',



    },
    forgotPasswordStep2: {
        forgotPwdTitle: 'Check your email',
        subTitle: 'We sent a password reset link to',
        enterEmail: 'Enter your email',
        openEmail: 'Open email app',
        dontEmail: 'Didn’t receive the email? ',
        resendEmail: 'Click to resend',
    },
    forgotPasswordStep3: {
        forgotPwdTitle: 'Set new password',
        subTitle: 'Your new password must be different to previously used passwords.',
        enterEmail: 'Enter your email',
        openEmail: 'Open email app',
        dontEmail: 'Didn’t receive the email?',
        resendEmail: 'Click to resend',
        char8: 'Must be at least 8 characters.',

    },
    forgotPasswordStep4: {
        forgotPwdTitle: 'Password reset',
        subTitle: 'Your password has been successfully reset. Click below to log in magically.',
    },
    surveyTitle: 'Where would you be more\nlikely to spend your Centz?',
    allTrancation: 'All Transaction',
    sleep: 'Sleep',
    movement: 'Movement',
    purchase: 'Purchase',
    centzBanks: 'Centz Bank',
    dailyTotal: 'Daily total:',
    rrp: 'RRP',
    pricePaid: 'Price Paid',
    discText: 'Centz discount',
    orderDetails: 'Order details',
    orderNum: 'Order number',
    orderDate: 'Order date',
    trackuingNum: 'Tracking Number',
    searchText: 'search marketplace',
    featureProduct: 'Featured products',
    center: 'center',
    category: 'Category',
    shopByCategory: 'Shop by category',
    price: 'Price',
    keepWalking: 'Keep walking!',
    keepWalkingSubText: 'If you walk an extra 0.5 miles you could earn another 50¢ off',
    productDetails: 'Hac pretium duis ultricies nullam tincidunt ut nisl, id enim. Aliquam in imperdiet suspendisse diam. Id sit tristique pretium, feugiat nisi. Dolor, eget sed magna massa.',
    addToCart: 'Add to cart',
    checkout: 'Checkout ',
    cartAdd: 'Added to you cart',
    checkoutNow: 'Checkout now',
    size: 'Size:',
    color: 'Color:',
    qty: 'Qty:',
    subTotal: 'Subtotal',
    delivery: 'Delivery',
    centzUsed: 'Centz used ',
    total: 'Total',
    paymentMethod: 'Payment method',
    shippingAddress: 'Shipping address',
    completePurchase: "Complete purchase",
    addNewPayment: 'Add New Payment Method',
    addNewAdd: "Add New Address",
    orderConform: 'Order confirmation',
    oderConformTitle: 'Thank you for your order',
    orderCancle: 'Oops! Payment failed',
    ordeeDetails: 'Order details',
    oderNum: 'Order number',
    oderDate: 'Order date',
    trackingNum: 'Tracking Number',
    backMarketPlace: 'Back to the marketplace',
    save: 'Save',
    cancel: 'Cancel',
    newPassword: 'New password',
    addnewADD: 'Add new address',
    addAddress: 'Add address',
    saveAs: 'Save as',
    privacy: 'Privacy policy',
    termConditions: 'Terms & Conditions',
    addCard: {
        title: 'Add new payment method',
        cardDetails: 'Card Details',
        NameOnCard: 'Name on card',
        cardNum: 'Card number',
        expiry: 'Expiry',
        cvv: 'CVV',
        defaultPayment: 'Set as default payment',
        billingAddress: 'Billing Address',
        addressLine1: 'Address Line 1*',
        addressLine2: 'Address Line 2',
        cityName: 'City Name*',
        state: 'State*',
        zip: 'Zip*',
        billingContact: 'Billing Contact',
        contactNumber: 'Contact number',
        emailAddress: 'Email address',
        cancel: 'Cancel',
        saveAs: 'Save as*',
        home: 'Home',
        office: 'Office',
        other: 'Other',
        setAsdefaultAddress: 'Set as default address',
        addPaymentMethod: 'Add payment method',
        shippingAdd: 'Shipping Addresses',
        addNewAdd: 'Add new address',
        saveAddress: 'Saved Address',
        savePayment:'Saved payment method',
        default: 'Default',
        edit: 'Edit',
        Office: 'Office',
        setAsDefault: 'Set As Default',
        country:'Country*',
        cancle:'Cancel',
        addBtn:'Add card'
    },
    account: {
        account: 'Account',
        profileSetting: 'Profile settings',
        statsHistory: 'Stats history',
        shippingAddresses: 'Shipping Addresses',
        paymentInformation: 'Payment information',
        favorites: 'Favorites',
        legal: 'Legal',
        termsConditions: 'Terms & Conditions',
        privacy: 'Privacy',
        deleteAccount: 'Delete Account',
        logout: 'Logout',
    },
    profile: {
        firstName: 'First Name',
        personalInfo: 'Personal information',
        surname: 'Surname',
        gender: 'Gender',
        dateofBirth: 'Date of birth',
        yourTrackerL: 'Your Tracker',
        linkNewTracker: 'Link new tracker',
        fitbitAlta: 'Fitbit Alta',
        unlink: 'unlink',
        password: 'Password',
        currentPwd: 'Current password',
        newPwd: 'New password'
    },
    statusHistory: {
        statsHistory1: 'Stats history',
        daily: 'Daily',
        weekly: 'Weekly',
        monthly: 'Monthly',
        today: 'Today - 21 Apr',
        stepsTaken: 'Steps taken',
        milesWalked: 'Miles walked',
        hoursSleep: 'Hours Sleep',
        centzMade: 'Centz made',
        caloriesBurnt: 'Calories burnt',
        iamgeText: 'In general, you make the most Centz on a Saturday.',
        Apr1824: '18 Apr  -  24 Apr',

    },
    dailyText: 'In general, you make the most Centz on a Saturday.',
    accountModelTexe: {
        deleteAccount: 'Delete Account',
        deleteAccSubText: 'Are you sure you want to delete your account? \n If you delete your Centavizer Account, all the data will be permanently deleted and cannot be retrieved.',
        dltAccount: 'Yes, Delete My Account',
        logout: 'Logout',
        logoutSubText: 'Are you sure you want to logout your account? You will be directed to login screen.',
        yesLogout: 'Yes, Logout',
        removePaymentMethod: 'Remove Payment Method',
        removeSubText: 'Are you sure you want to remove this payment method permanently?',
        removeAcc: 'Yes, Remove',
        removeAddress: 'Remove Address',
        removeAddSubText: 'Are you sure you want to remove this address permanently?',
        yesRemove: 'Yes, Remove',
        unlinkTracker:'Unlink Tracker',
        unlinkTrackerSub:'Are you sure you want to unlink your fitness tracker?',
        yesUnlink :'Yes, Unlink',
    },
    addAdd: {

        shippingAdd: 'Shipping Addresses',
        addNewAdd: 'Add new address',
        saveAddress: 'Saved Address',
        home: 'Home',
        default: 'Default',
        edit: 'Edit',
        Office: 'Office',
        setAsDefault: 'Set As Default',
        editAdd:'Edit address',
        editSaveAdd:'Save Changes',
        editCancle:'Remove address'
        
    },
    linkTracker:'Link your tracker to see your activity history.',
    syncDevice:'Sync your Device',
    resync:"Resync Your Device",
    selectCorrectTracker: "You have selected wrong account/tracker Please select the correct tracker.",
    back: 'back'
};
