export const Images = {
    dots: require('../images/dots.png'),
    heart: require('../images/heart.png'),
    heart2: require('../images/heart2.png'),
    login: require('../images/login.png'),
    page1: require('../images/page1.png'),
    page2: require('../images/page2.png'),
    page3: require('../images/page3.png'),
    logoCentavizer: require('../images/logoCentavizer.png'),
    google: require('../images/google.png'),
    fb: require('../images/facebook.png'),
    apple: require('../images/apple.png'),
    tea: require('../images/tea.jpeg'),
    greenTea: require('../images/greenTea.jpg'),
    cake: require('../images/cake.jpeg'),
    coffee: require('../images/coffee.jpeg'),
    food: require('../images/food.png'),
    leftBlueHalf: require('../images/leftBlueHalf.png'),
    leftOrangeHalf: require('../images/leftOrangeHalf.png'),
    rightBlueHalf: require('../images/rightBlueHalf.png'),
    rightGreenHalf: require('../images/rightGreenHalf.png'),
    rightMinHalfBlue: require('../images/rightMinHalfBlue.png'),
    rightOrangeHalf: require('../images/rightOrangeHalf.png'),
    bottomBlueround: require('../images/bottomBlueround.png'),
    bottomBlueRoundThik: require('../images/bottomBlueRoundThik.png'),
    bottomGreen: require('../images/bottomGreen.png'),
    bottomOrangeround: require('../images/bottomOrangeround.png'),
    watch: require('../images/watch.png'),
    sync: require('../images/sync.png'),
    synced2: require('../images/synced2.png'),
    papaJohn: require('../images/papaJohn.png'),
    pizaheart: require('../images/pizaheart.png'),
    dominoz: require('../images/dominoz.png'),
    headPhone: require('../images/headPhone.png'),
    bg2: require('../images/bg2.png'),
    cardBG: require('../images/cardBG.png'),
    colorBrush: require('../images/colorBrush.png'),
    gogals: require('../images/gogals.png'),
    gym: require('../images/gym.png'),
    mobile: require('../images/mobile.png'),
    shirt: require('../images/shirt.png'),
    watches: require('../images/watches.png'),
    waterBottal: require('../images/waterBottal.png'),
    default: require('../images/default.jpeg'),
    profilePic: require('../images/ProfilePic.jpeg'),
    accountBG: require('../images/accountBG.jpeg'),
    smartBelt: require('../images/SmartBelt.png'),
    favBg1: require('../images/favBg1.png'),
    FavBg2: require('../images/FavBg2.png'),
    FavBg3: require('../images/FavBg3.png'),
    FavBg4: require('../images/FavBg4.png'),
    samsung:require('../images/samsung.png'),
    masterCard:require('../images/masterCard.png'),
    visa:require('../images/visa.png'),
    next:require('../images/next.png'),
    ground:require('../images/ground.jpeg'),
    pizza:require('../images/pizza.jpeg'),
    cocacoola:require('../images/cocacoola.jpeg'),
    theBird:require('../images/theBird.png'),
    map:require('../images/map.png'),
    pizz3:require('../images/pizz3.jpeg'),
    car:require('../images/car.jpeg'),
    doctor:require('../images/doctor.jpeg'),
    entertainment:require('../images/entertainment.jpeg'),
    health:require('../images/health.jpeg'),
    nightLife:require('../images/nightLife.jpeg'),
    shopping:require('../images/shopping.jpeg'),
    spa:require('../images/spa.jpeg'),
    coffeeIcon:require('../images/coffeeIcon.png'),
    fitness:require('../images/fitness.png'),
    restaurants:require('../images/restaurants.jpeg'),
    bar:require('../images/bar.png'),
    restarant:require('../images/restarant.png'),
    selectUnion:require('../images/selectUnion.png'),
    edit:require('../images/edit.png'),

};
